version: '3'
services:
  redis:
    image: redis:alpine
    container_name: redis-container
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      POSTGRES_DB: photoshare
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    image: sergiokapone/SnapshopExchange:latest
    container_name: SnapshopExchange
    ports:
      - "8000:8000"
    depends_on:
      - redis
      - postgres

volumes:
  redis_data:
  postgres_data:

