"""changed photo & tags

Revision ID: 251d7982b553
Revises: 09db308a3a3d
Create Date: 2023-09-01 18:09:50.300845

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '251d7982b553'
down_revision: Union[str, None] = '09db308a3a3d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('photo_m2m_tags',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('photo_id', sa.Integer(), nullable=True),
    sa.Column('tag_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], ),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('photo_tags')
    op.add_column('photos', sa.Column('created_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('photos', 'created_at')
    op.create_table('photo_tags',
    sa.Column('photo_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('tag_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['photo_id'], ['photos.id'], name='photo_tags_photo_id_fkey'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], name='photo_tags_tag_id_fkey')
    )
    op.drop_table('photo_m2m_tags')
    # ### end Alembic commands ###