"""photo2

Revision ID: 3c938ef2b655
Revises: ee9b638ace32
Create Date: 2023-08-31 19:53:57.688185

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c938ef2b655'
down_revision: Union[str, None] = 'ee9b638ace32'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('user_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'photos', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'photos', type_='foreignkey')
    op.drop_column('photos', 'user_id')
    # ### end Alembic commands ###
