"""change column name

Revision ID: 692c63d675ca
Revises: 3c938ef2b655
Create Date: 2023-09-01 15:45:28.516202

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '692c63d675ca'
down_revision: Union[str, None] = '3c938ef2b655'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('cloud_url', sa.String(length=200)))
    op.add_column('photos', sa.Column('description', sa.String(length=500), nullable=True))
    op.drop_column('photos', 'content')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('photos', sa.Column('content', sa.VARCHAR(length=200), autoincrement=False, nullable=False))
    op.drop_column('photos', 'description')
    op.drop_column('photos', 'cloud_url')
    # ### end Alembic commands ###
